// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/Users/patsfan753/Desktop/auauAnalysis/emcalSEPDcorrelations/macros/./analyzeRun24or25auau.cpp";

#endif
